using System.Net.Http.Headers;
using System.Security.Cryptography;

namespace LibraryManangement
{
    internal class Program
    {
        //Library card is generated by the MYTSQL auto increment 
        //Option for logout back 
        //View book that student has borrowed
        //x ki jagah kuch aacha nam
        //account deletion
        readonly static DBConnection db = DBConnection.Instance();
        static void Main(string[] args)
        {
            Console.WriteLine("Loading...");
            Console.WriteLine("(press Enter)");
            Console.ReadKey();
            db.Server = "localhost";
            db.DatabaseName = "library";
            db.UserName = "root";
            db.Password = "root";
            Console.WriteLine("---Welcome To Library----\n");
            if (db.IsConnected())
            {
                Console.Write("1. Student\n2. Employee\nEnter Your Choice: ");
                int e = Convert.ToInt32(Console.ReadLine());
                if (e == 2)
                {
                    Console.Write("Enter password : ");
                    OperationsOnBooks Operation = new OperationsOnBooks();
                    if (Operation.IsPasswordValid(Console.ReadLine()))
                    {
                        Console.WriteLine("WELCOME SIR/MAM!\n");
                        int ch;
                        do
                        {
                            Console.WriteLine("1. Add Book\n2. Update Book Information\n3. Update Number Of Quantity Of Book\n4. Remove Book\n5. Add Multiple Books\n6. Display all books\n7. Students Information\n8. List of all borrowers\n9. List of borrowers with pending return\n10. Exit");
                            Console.Write("Enter your choice : ");
                            ch = Convert.ToInt32(Console.ReadLine());
                            BookInfo Book = new BookInfo();
                            switch (ch)
                            {
                                case 1:
                                    Console.Write("\nEnter Book Id : ");
                                    Book.BookId = Console.ReadLine().ToUpper();
                                    Console.Write("\nEnter Book Name: ");
                                    Book.BookName = Console.ReadLine().ToUpper();
                                    Console.Write("\nAuthor Name : ");
                                    Book.AuthorName = Console.ReadLine();
                                    Console.Write("\nDescription : ");
                                    Book.Description = Console.ReadLine();
                                    Console.Write("\nBook Price (In Rupees) : ");
                                    Book.BookPrice = Convert.ToDecimal(Console.ReadLine());
                                    Console.Write("\nAvailable Quantity : ");
                                    Book.AvailableQuantity = Convert.ToInt32(Console.ReadLine());
                                    int x = Operation.AddBook(db, Book);
                                    if (x == -1)
                                        Console.WriteLine("Something went wrong");
                                    else
                                        Console.WriteLine("Book Added Successfully");
                                    break;
                                case 2:
                                    String BookID;
                                    Console.Write("\nEnter BookID that you want to update : ");
                                    BookID = Console.ReadLine();
                                    Console.Write("\nEnter BookId : ");
                                    Book.BookId = Console.ReadLine().ToUpper();
                                    Console.Write("\nEnter Book Name : ");
                                    Book.BookName = Console.ReadLine().ToUpper();
                                    Console.Write("\nEnter Author Name : ");
                                    Book.AuthorName = Console.ReadLine();
                                    Console.Write("\nEnter Description : ");
                                    Book.Description = Console.ReadLine();
                                    Console.Write("\nEnter Price(In Rupees) : ");
                                    Book.BookPrice = Convert.ToDecimal(Console.ReadLine());
                                    Console.Write("\nEnter Quantity Available : ");
                                    Book.AvailableQuantity = Convert.ToInt32(Console.ReadLine());
                                    x = Operation.UpdateBookInfo(db, Book, BookID);
                                    if (x == 1)
                                        Console.WriteLine("\nBook is Updated Successfully!");
                                    if (x == 0)
                                        Console.WriteLine("\nBook Not Found!");
                                    if (x == -1)
                                        Console.WriteLine("\nSomething went wrong!");
                                    break;
                                case 3:
                                    BookInfo bookInfo = new BookInfo();
                                    Console.Write("\nEnter BookID that you want to update : ");
                                    bookInfo.BookId = Console.ReadLine();
                                    Console.Write("\nEnter updated quantity : ");
                                    bookInfo.AvailableQuantity= Convert.ToInt32(Console.ReadLine());
                                    x = Operation.UpdateBookAvailableQuantity(db, bookInfo);
                                    if (x == 1)
                                        Console.WriteLine("\nBook Quantity is Updated Successfuly!");
                                    if (x == 0)
                                        Console.WriteLine("\nNo Book_Id formed");
                                    if (x == -1)
                                        Console.WriteLine("\nSomething went wrong!");
                                    break;
                                case 4:
                                    Console.Write("\nEnter Book ID that you want to deleted : ");
                                    String TitleId = Console.ReadLine();
                                    x = Operation.RemoveBookFromLibrary(db, TitleId);
                                    if (x == 0)
                                        Console.WriteLine("\nBook Not Found!");
                                    if (x == 1)
                                        Console.WriteLine("\nBook Deleted Successfully!");
                                    if (x == -1)
                                        Console.WriteLine("\nSomething went wrong!");
                                    break;
                                case 5:
                                    char ch1;
                                    do
                                    {
                                        Console.Write("\nEnter Book Id : ");
                                        Book.BookId = Console.ReadLine().ToUpper();
                                        Console.Write("\nEnter Book Name: ");
                                        Book.BookName = Console.ReadLine().ToUpper();
                                        Console.Write("\nAuthor Name : ");
                                        Book.AuthorName = Console.ReadLine();
                                        Console.Write("\nDescription : ");
                                        Book.Description = Console.ReadLine();
                                        Console.Write("\nBook Price (In Ruspees) : ");
                                        Book.BookPrice = Convert.ToDecimal(Console.ReadLine());
                                        Console.Write("\nAvailable Quantity : ");
                                        Book.AvailableQuantity = Convert.ToInt32(Console.ReadLine());
                                        x = Operation.AddBook(db, Book);
                                        if (x == -1)
                                            Console.WriteLine("Something went wrong");
                                        else
                                            Console.WriteLine("Book Added Successfully");
                                        Console.Write("\nDo you want to add more books? (y/n) : ");
                                        ch1 = Convert.ToChar(Console.ReadLine());
                                    } while (ch1 == 'Y' || ch1 == 'y');
                                    break;
                                case 6:
                                    List<BookInfo> Books = new List<BookInfo>();
                                    Books = Operation.BookInformation(db);
                                    printElementsOfBook(Books,0);
                                    break;
                                case 7:
                                    List<BorrowerInfo> lst = new List<BorrowerInfo>();
                                    lst=Operation.DisplayRegisteredStudents(db);
                                    printElementsOfStudent(lst);
                                    break;
                                case 8:
                                    List<BorrowedBook> borrowedBooks = new List<BorrowedBook>();
                                    borrowedBooks = Operation.DisplayDetailsOfBorrowedBooks(db);
                                    printElementsOfBorrowedBooks(borrowedBooks,0);
                                    break;
                                case 9:
                                    List<BorrowedBook> borrowedBookswithpending = new List<BorrowedBook>();
                                    borrowedBookswithpending = Operation.DisplayDetailsOfBorrowedBooksWithPendingReturn(db);
                                    printElementsOfBorrowedBooks(borrowedBookswithpending,1);
                                    break;
                                case 10:
                                    break;
                                default:
                                    Console.WriteLine("Wrong Choice! Please try again.");
                                    break;
                            }
                        } while (ch != 10);
                        db.Close();
                    }
                    else
                    {
                        Console.WriteLine("Wrong Password");
                        db.Close();
                    }
                }
                else if (e == 1)
                {
                    Console.WriteLine("\n---Welcome To Student Portal!---");
                    Console.Write("1. Login\n2. Create Account\nEnter Choice: ");
                    int choice = Convert.ToInt32(Console.ReadLine());
                    OperationOnBorrowers OperationForUser = new OperationOnBorrowers();
                    if (choice!=1&&choice!=2)
                        Console.WriteLine("Wrong Choice! Please try again.");
                    else if (choice == 2)
                    {
                        BorrowerInfo borrowerInfo = new BorrowerInfo();
                        Console.Write("\nEnter Aadhar Number : ");
                        borrowerInfo.BorrowerId = Convert.ToInt32(Console.ReadLine());
                        Console.Write("\nEnter First Name : ");
                        borrowerInfo.FirstName = Console.ReadLine();
                        Console.Write("\nEnter Last Name : ");
                        borrowerInfo.LastName = Console.ReadLine();
                        Console.Write("\nEnter Phone Number : ");
                        borrowerInfo.PhoneNumber = Console.ReadLine();
                        Console.Write("\nEnter Permanent Address : ");
                        borrowerInfo.Address= Console.ReadLine();
                        Console.Write("\nEnter College Email : ");
                        borrowerInfo.Email = Console.ReadLine();
                        int x = OperationForUser.CreateAccount(db, borrowerInfo);
                        if (x == -1)
                            Console.WriteLine("Try Again With Valid Values");
                        else if(x==0)
                            Console.WriteLine("Library Number can't be fetched!");
                        else
                        {
                            Console.WriteLine("Account Created Successfully!");
                            Console.WriteLine("Your Library Card Number is : " + x);
                        }
                    }
                    else
                    {
                        BorrowerInfo borrowerInfo = new BorrowerInfo();
                        Console.Write("\nEnter Your Library number : ");
                        borrowerInfo.LibraryCardNum = Convert.ToInt32(Console.ReadLine());
                        Console.Write("\nEnter Your Aadhar/ID number : ");
                        borrowerInfo.BorrowerId= Convert.ToInt32(Console.ReadLine());
                        bool s = OperationForUser.IsUserValid(db,borrowerInfo);
                        if (s)
                        {
                            int ch;
                            do
                            {
                                Console.Write("1. Display Available Books\n2. Borrow A Book\n3. Return A Book\n4. Borrowed Books Detail\n5. Delete Account\n6. Exit\nEnter Your Choice: ");
                                ch = Convert.ToInt32(Console.ReadLine());
                                switch (ch)
                                {
                                    case 1:
                                        List<BookInfo> lst = new List<BookInfo>();
                                        lst = OperationForUser.DisplayAvailableBookDetails(db);
                                        printElementsOfBook(lst,1);
                                        break;
                                    case 2:
                                        Console.Write("\nEnter Book Id that you want to borrow : ");
                                        BookInfo bookid = new BookInfo();
                                        bookid.BookId= Console.ReadLine().ToUpper();
                                        int x = OperationForUser.BorrowABook(db,borrowerInfo,bookid);
                                        if(x==2)
                                            Console.WriteLine("You have already borrowed 3 books! Please return a book before borrowing another.");
                                        else if (x == 1)
                                            Console.WriteLine("Book Borrowed Successfully!");
                                        else if (x == 0)
                                            Console.WriteLine("Book Not Found!");
                                        else
                                            Console.WriteLine("Something went wrong! Please try again.");
                                        break;
                                    case 3:
                                        Console.Write("\nEnter Book Id that you want to return : ");
                                        BookInfo bookid1 = new BookInfo();
                                        bookid1.BookId = Console.ReadLine().ToUpper();
                                        x = OperationForUser.ReturnABook(db, borrowerInfo, bookid1);
                                        if (x == 1)
                                            Console.WriteLine("Book Returned Successfully!");
                                        else if (x == 0)
                                            Console.WriteLine("No such book is issued to you!");
                                        else if (x == -1)
                                            Console.WriteLine("Something went wrong!");
                                        else
                                            Console.WriteLine("You need to pay fine of "+ x+"Rupees");
                                        break;
                                    case 4:
                                        List<BorrowedBook> borrowedBooks = new List<BorrowedBook>();
                                        borrowedBooks = OperationForUser.BorrowedBooksDetail(db, borrowerInfo);
                                        if (borrowedBooks.Count == 0)
                                            Console.WriteLine("You have not borrowed any books yet!");
                                        else
                                            printElementsOfBorrowedBooks(borrowedBooks, 2);
                                        break;
                                    case 5:
                                        Console.Write("\nAre you sure you want to delete your account? (y/n): ");
                                        char confirm = Convert.ToChar(Console.ReadLine());
                                        if (confirm == 'y' || confirm == 'Y')
                                        {
                                            int result = OperationForUser.DeleteAccount(db, borrowerInfo);
                                            if (result == 1)
                                                Console.WriteLine("Account deleted successfully!");
                                            else if (result == 0)
                                                Console.WriteLine("No such account found!");
                                            else if(result == 2)
                                                Console.WriteLine("You have borrowed books! Please return them before deleting your account.");
                                            else if(result == -1)
                                                Console.WriteLine("Something went wrong! Please try again.");
                                        }
                                        else
                                        {
                                            Console.WriteLine("Account deletion cancelled.");
                                        }
                                        break;
                                    case 6:
                                        break;
                                    default:
                                        Console.WriteLine("Wrong Choice! Please try again.");
                                        break;
                                }

                            } while (ch!=6);
                            db.Close();
                        }
                        else
                        {
                         Console.WriteLine("Invalid Library Card Number or Aadhar/ID number");
                         db.Close();
                        }
                    }
                }
            }
        }
        public static void printElementsOfBook(List<BookInfo> lst,int x)
        {
            // x = 0 means it is called from employee operations, so print book price
            // x = 1 means it is called from student operations, so do not print book price
            if (lst.Count == 0)
            {
                Console.WriteLine("No Books Found!");
                return;
            }
            foreach (var i in lst)
            {
                Console.WriteLine("\nBook Id : " + i.BookId);
                Console.WriteLine("Book Name : " + i.BookName);
                Console.WriteLine("Author Name : " + i.AuthorName);
                Console.WriteLine("Description : " + i.Description);
                if (x == 0)
                {
                    Console.WriteLine("Book Price : " + i.BookPrice);
                    Console.WriteLine("Available Quantity : " + i.AvailableQuantity);
                }
                Console.WriteLine("-------------------------------");
            }
                return;
        }
        public static void printElementsOfStudent(List<BorrowerInfo> lst)
        {
            if (lst.Count == 0)
            {
                Console.WriteLine("No such Student found!");
                return;
            }
            foreach (var i in lst)
            {
                Console.WriteLine("\nLibrary Card Number : " + i.LibraryCardNum);
                Console.WriteLine("Borrower Id : " + i.BorrowerId);
                Console.WriteLine("First Name : " + i.FirstName);
                Console.WriteLine("Last Name : " + i.LastName);
                Console.WriteLine("Phone Number : " + i.PhoneNumber);
                Console.WriteLine("Address : " + i.Address);
                Console.WriteLine("Email : " + i.Email);
                Console.WriteLine("Borrowed Books Count : " + i.BorrowedBooksCount);
                Console.WriteLine("-------------------------------");
            }
        }
        public static void printElementsOfBorrowedBooks(List<BorrowedBook> lst, int x)
        {
            if (lst.Count == 0)
            {
                Console.WriteLine("No Borrowed Books Found!");
                return;
            }
            if (x == 0)
            {
                foreach (var i in lst)
                {
                    Console.WriteLine("\nIssued To Library Card Number : " + i.IssuedToLibraryCardNum);
                    Console.WriteLine("Book Id : " + i.BookId);
                    Console.WriteLine("Issued Date : " + i.IssuedDate);
                    Console.WriteLine("Return Date : " + i.ReturnDate);
                    Console.WriteLine("Fine : " + i.Fine);
                    Console.WriteLine("-------------------------------");
                }
                return;
            }
            if (x == 2)
            {
                foreach (var i in lst)
                {
                    Console.WriteLine("Book Id : " + i.BookId);
                    Console.WriteLine("Issued Date : " + i.IssuedDate);
                    Console.WriteLine("-------------------------------");
                }
                return;
            }
            foreach (var i in lst)
            {
                Console.WriteLine("\nIssued To Library Card Number : " + i.IssuedToLibraryCardNum);
                Console.WriteLine("Book Id : " + i.BookId);
                Console.WriteLine("Issued Date : " + i.IssuedDate);
                Console.WriteLine("-------------------------------");
            }
        }
    }
}
